# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('sort_weight', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=64)),
                ('link', models.CharField(blank=True, max_length=256)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plainmenu.Menu')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set([('path', 'menu')]),
        ),
    ]
