# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plainmenu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(1, 'None'), (2, 'New window')], default=1),
        ),
        migrations.AddField(
            model_name='menu',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plainmenu.Group'),
        ),
    ]
