# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plainmenu', '0002_auto_20170109_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='identifier',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
