# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plainmenu', '0003_auto_20170111_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='identifier',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('identifier', 'group')]),
        ),
    ]
