# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plainmenu', '0004_auto_20170111_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
