# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plainmenu', '0005_auto_20170111_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='hint',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
